
language: php

php:
  - 7.1
  - 7.2

env:
  APP_KEY: XTe0nzaJt90Utv23jJQ3zti4RXYrIiyP
  JWT_SECRET: YuJwjOCrWGWIdyq95yP89qUKPTvQ3BQK

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit